version: "3.2"

# docker-compose.yml build 방법
# docker-compose up

services:
  server:
    container_name: server
    
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/srv/server
    restart: always
    expose:
      - "8000"
    networks:
      - nginx_bridge
      - server_database_bridge
    depends_on:
      - database

  client:
    container_name: client
    build:
      context: ./front
      dockerfile: Dockerfile
    volumes:
      - ./front:/srv/client
    restart: always
    environment:
      - SERVER_ADDR=server
    expose:
      - "3000"
    ports:
      - "3000:3000"
    networks:
      - nginx_bridge
    depends_on:
      - server

  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: always
    ports:
      - "80:80"
    depends_on:
      - server
      - client
    networks:
      - nginx_bridge
      
  database:
    image: mysql:5.7
    container_name: database
    env_file: .env
    volumes:
      - ./db_data:/var/lib/mysql-files
    restart: unless-stopped
    expose:
      - "3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
     - MYSQL_ROOT_PASSWORD=${DBPASSWORD}
     - MYSQL_DATABASE=${DBNAME}
    networks:
      - server_database_bridge

networks:
  nginx_bridge:
    driver: bridge
  server_database_bridge:
    driver: bridge